name: Prod Deploy

on:
  push:
    branches: [ prod ]

jobs:
  test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup Node v16
        uses: actions/setup-node@v1
        with:
          node-version: v16.16.0

      - uses: actions/cache@v3
        with:
          path: |
            .next
            .yarn/cache
            ./node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn export

      - name: Deploy Gh-Pages ðŸš€
        uses: hpcodecraft/action-deploy-workspace-to-repo@v2.2
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.DECOO_PAT }}
          SRC_FOLDER: out
          DEST_OWNER: decooio
          DEST_REPO: cloud3-home-prod-deploy
          DEST_BRANCH: main
          DEST_FOLDER: docs